[{
    facilityType: "elementary",
    fieldType: "football",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "primary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Field hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "12U",
        priority: "primary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "primary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "football",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "primary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "football",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "primary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "football",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "primary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
]