const sportsData = [
  {
    facilityType: "elementary",
    fieldType: "baseball",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "primary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "primary",
        id: 80,
        sportsAgeId: 7,
      },
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "secondary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Field Hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate",
        ageGroup: "12U",
        priority: "secondary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "baseball",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 300,
      baseballWidth: 360,
    },
    compatibleSports: [
      {
        name: "Baseball",
        ageGroup: "14U",
        priority: "primary",
        id: 8,
        sportsAgeId: 5,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "primary",
        id: 80,
        sportsAgeId: 7,
      },
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "secondary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Field Hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate",
        ageGroup: "12U",
        priority: "secondary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "baseball",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 330,
      baseballWidth: 390,
    },
    compatibleSports: [
      {
        name: "Baseball",
        ageGroup: "18U",
        priority: "primary",
        id: 8,
        sportsAgeId: 7,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "primary",
        id: 80,
        sportsAgeId: 7,
      },
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "secondary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Field Hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate",
        ageGroup: "12U",
        priority: "secondary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "park",
    fieldType: "baseball",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 300,
      baseballWidth: 360,
    },
    compatibleSports: [
      {
        name: "Baseball",
        ageGroup: "14U",
        priority: "primary",
        id: 8,
        sportsAgeId: 5,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "primary",
        id: 80,
        sportsAgeId: 7,
      },
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "secondary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Field Hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate",
        ageGroup: "12U",
        priority: "secondary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "baseball",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "primary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "primary",
        id: 80,
        sportsAgeId: 7,
      },
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "secondary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "secondary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Field Hockey",
        ageGroup: "12U",
        priority: "secondary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate",
        ageGroup: "12U",
        priority: "secondary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "secondary",
        id: 54,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "elementary",
    fieldType: "basketball",
    dimensions: { length: 74, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "12U",
        priority: "primary",
        id: 9,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "basketball",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "basketball",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "park",
    fieldType: "basketball",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "basketball",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "elementary",
    fieldType: "soccer",
    dimensions: {
      length: 210,
      width: 135,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "12U",
        priority: "primary",
        id: 79,
        sportsAgeId: 4,
      },
      {
        name: "Field hockey",
        ageGroup: "12U",
        priority: "primary",
        id: 31,
        sportsAgeId: 4,
      },
      {
        name: "Lacrosse",
        ageGroup: "12U",
        priority: "primary",
        id: 54,
        sportsAgeId: 4,
      },
      {
        name: "Rugby",
        ageGroup: "12U",
        priority: "primary",
        id: 73,
        sportsAgeId: 4,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "12U",
        priority: "primary",
        id: 89,
        sportsAgeId: 4,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "soccer",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "primary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "primary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "primary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "soccer",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "primary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "primary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "primary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "park",
    fieldType: "soccer",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "primary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "primary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "primary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "soccer",
    dimensions: {
      length: 300,
      width: 150,
      baseballLength: 225,
      baseballWidth: 275,
    },
    compatibleSports: [
      {
        name: "Soccer",
        ageGroup: "18U",
        priority: "primary",
        id: 79,
        sportsAgeId: 7,
      },
      {
        name: "Field hockey",
        ageGroup: "18U",
        priority: "primary",
        id: 31,
        sportsAgeId: 7,
      },
      {
        name: "Lacrosse",
        ageGroup: "18U",
        priority: "primary",
        id: 54,
        sportsAgeId: 7,
      },
      {
        name: "Rugby",
        ageGroup: "18U",
        priority: "primary",
        id: 73,
        sportsAgeId: 7,
      },
      {
        name: "Ultimate Frisbee",
        ageGroup: "18U",
        priority: "primary",
        id: 89,
        sportsAgeId: 7,
      },
      {
        name: "Football",
        ageGroup: "12U",
        priority: "secondary",
        id: 37,
        sportsAgeId: 4,
      },
      {
        name: "Baseball",
        ageGroup: "12U",
        priority: "secondary",
        id: 8,
        sportsAgeId: 4,
      },
      {
        name: "Softball",
        ageGroup: "18U",
        priority: "secondary",
        id: 80,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "elementary",
    fieldType: "tennis",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Tennis",
        ageGroup: "18U",
        priority: "primary",
        id: 87,
        sportsAgeId: 7,
      },
      {
        name: "Pickleball",
        ageGroup: "18U",
        priority: "primary",
        id: 63,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "tennis",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Tennis",
        ageGroup: "18U",
        priority: "primary",
        id: 87,
        sportsAgeId: 7,
      },
      {
        name: "Pickleball",
        ageGroup: "18U",
        priority: "primary",
        id: 63,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "tennis",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Tennis",
        ageGroup: "18U",
        priority: "primary",
        id: 87,
        sportsAgeId: 7,
      },
      {
        name: "Pickleball",
        ageGroup: "18U",
        priority: "primary",
        id: 63,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "park",
    fieldType: "tennis",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Tennis",
        ageGroup: "18U",
        priority: "primary",
        id: 87,
        sportsAgeId: 7,
      },
      {
        name: "Pickleball",
        ageGroup: "18U",
        priority: "primary",
        id: 63,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "tennis",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Tennis",
        ageGroup: "18U",
        priority: "primary",
        id: 87,
        sportsAgeId: 7,
      },
      {
        name: "Pickleball",
        ageGroup: "18U",
        priority: "primary",
        id: 63,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "elementary",
    fieldType: "volleyball",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Volleyball",
        ageGroup: "12U",
        priority: "primary",
        id: 90,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "volleyball",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Volleyball",
        ageGroup: "14U",
        priority: "primary",
        id: 90,
        sportsAgeId: 5,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "volleyball",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Volleyball",
        ageGroup: "18U",
        priority: "primary",
        id: 90,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "park",
    fieldType: "volleyball",
    dimensions: { length: 78, width: 36 },
    compatibleSports: [
      {
        name: "Volleyball",
        ageGroup: "18U",
        priority: "primary",
        id: 90,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "elementary",
    fieldType: "gym",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "12U",
        priority: "primary",
        id: 9,
        sportsAgeId: 4,
      },
      {
        name: "Volleyball",
        ageGroup: "12U",
        priority: "primary",
        id: 90,
        sportsAgeId: 4,
      },
    ],
  },
  {
    facilityType: "middle",
    fieldType: "gym",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
      {
        name: "Volleyball",
        ageGroup: "18U",
        priority: "primary",
        id: 90,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "high",
    fieldType: "gym",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
      {
        name: "Volleyball",
        ageGroup: "18U",
        priority: "primary",
        id: 90,
        sportsAgeId: 7,
      },
    ],
  },
  {
    facilityType: "private",
    fieldType: "gym",
    dimensions: { length: 94, width: 50 },
    compatibleSports: [
      {
        name: "Basketball",
        ageGroup: "18U",
        priority: "primary",
        id: 9,
        sportsAgeId: 7,
      },
      {
        name: "Volleyball",
        ageGroup: "18U",
        priority: "primary",
        id: 90,
        sportsAgeId: 7,
      },
    ],
  },
];

export default sportsData;